services:
  db:
    image: postgres:latest
    container_name: perfume-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: perfume_root_123
      POSTGRES_DB: perfume
      PGDATA: /var/lib/postgresql/data/pgdata # Added explicitly to fix pg_ctlcluster issue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d perfume"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: perfume-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-bucket:
    image: minio/mc:latest
    container_name: perfume-minio-bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 minioadmin minioadmin; do sleep 2; done;
      mc mb --ignore-existing local/perfumes;
      mc anonymous set download local/perfumes;
      "

  # backend:
  #   build: .
  #   container_name: perfume-backend
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     minio-bucket:
  #       condition: service_completed_successfully
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/perfume
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: perfume_root_123
  #     STORAGE_S3_ENDPOINT: http://minio:9000
  #     STORAGE_S3_PUBLIC_URL: http://localhost:9000
  #     STORAGE_S3_ACCESS_KEY: minioadmin
  #     STORAGE_S3_SECRET_KEY: minioadmin
  #     STORAGE_S3_BUCKET_NAME: perfumes
  #     APP_FRONTEND_BASE_URL: http://localhost
  #     JWT_SECRET: change-me-for-local-compose
  #   ports:
  #     - "8080:8080"
      
  # frontend:
  #   build: ./frontend
  #   container_name: perfume-frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "80:80"

volumes:
  postgres_data:
  minio_data: